---
- name: asdf install rust
  asdf:
    plugin: rust
    versions: "{{ versions }}"
    global: "{{ global | default(versions[0]) }}"

- include_tasks: rustup.yml
  loop: "{{ versions }}"
  vars:
    version: "{{ item }}"
