---
- name: asdf local
  command: asdf local golang {{ version }}

- name: go get
  command: go get {{ item }}
  loop: []
    # - github.com/x-motemen/gore

- name: asdf reshim
  command: asdf reshim golang
