---
- name: asdf local
  command: asdf local golang {{ version }}

- name: go install
  command: go install {{ item }}
  loop:
    # - github.com/x-motemen/gore
    - github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
    - github.com/google/go-jsonnet/cmd/jsonnet-lint@latest

- name: asdf reshim
  command: asdf reshim golang
