---
- name: asdf local
  command: asdf local golang {{ version }}

- name: go install
  command: go install {{ item }}
  loop:
    - github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
    - github.com/go-delve/delve/cmd/dlv@latest
    - github.com/google/go-jsonnet/cmd/jsonnet-lint@latest
    # - github.com/x-motemen/gore

- name: asdf reshim
  command: asdf reshim golang
