---
- name: asdf install golang
  asdf:
    plugin: golang
    versions: "{{ versions }}"
    global: "{{ global | default(versions[0]) }}"

- include_tasks: go_get.yml
  loop: "{{ versions }}"
  vars:
    version: "{{ item }}"
