---
- name: asdf plugin add golang
  command: asdf plugin add golang
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/golang"
  ignore_errors: true

- name: asdf install golang
  command: "asdf install golang {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/installs/golang/{{ item }}"
  with_items: "{{ versions }}"

- name: asdf global golang
  command: "asdf global golang {{ global | default(versions[0]) }}"

- name: asdf list golang
  command: asdf list golang
  register: asdf_list_golang
  changed_when: false
  check_mode: false

- name: asdf uninstall golang
  command: "asdf uninstall golang {{ item }}"
  with_items: "{{ asdf_list_golang.stdout.split('\n') | map('trim') | list }}"
  when: >-
    item not in versions
