---
- hosts: default
  roles:
    - homebrew
    - role: asdf
      asdf_version: v0.7.8
    - role: clojure
      versions: ["1.10.1"]
    - dev_dir
    - docker
    - editorconfig
    - emacs
    - role: erlang
      versions: ["23.0.3"]
      elixir:
        versions: ["1.10.4-otp-23"]
    - role: git
      user_name: ne-sachirou
      user_email: ne-sachirou@hatena.ne.jp
    - role: golang
      versions:
        - "1.15"
        - "1.14.7"
        - "1.12.17"
    - role: haskell
      versions: ["8.10.2"]
    - role: hatenablog
      private_values_project: hatena
    - mackerel-agent
    - role: nodejs
      versions:
        - "14.8.0"
        - "12.14.0"
    - role: perl
      versions: ["5.32.0"]
    - role: python
      versions: ["3.8.5"]
    - role: ruby
      versions:
        - "2.7.1"
        - "2.5.7"
    - scala
    - role: ssh
      private_values_project: hatena
    - vagrant
    - vim
    - role: vscode
      vscode_extensions:
        - EditorConfig.EditorConfig
        - GitHub.vscode-pull-request-github
        - JakeBecker.elixir-ls
        - MS-CEINTL.vscode-language-pack-ja
        - dbaeumer.vscode-eslint
        - eamodio.gitlens
        - esbenp.prettier-vscode
        - golang.go
        - humao.rest-client
        - jebbs.plantuml
        - marp-team.marp-vscode
        - mjmcloug.vscode-elixir
        - ms-python.python
        - ms-vsliveshare.vsliveshare
        - msjsdiag.debugger-for-chrome
        - pgourlain.erlang
        - scala-lang.scala
        - scalameta.metals
        - taichi.vscode-textlint
        - uraway.hatenablogger
        - vscodevim.vim
    - zsh
