---
- hosts: default
  roles:
    - homebrew
    - role: asdf
      asdf_version: v0.12.0
    - role: clojure
      versions: ["1.11.1.1403"]
    - dev_dir
    - docker
    - editorconfig
    - emacs
    - role: erlang
      versions: ["26.0.2"]
      elixir:
        versions: ["1.15.4-otp-26"]
    - gcloud
    - role: git
      user_name: ne-sachirou
      user_email: ne-sachirou@hatena.ne.jp
    - role: golang
      versions:
        - "1.21.0"
    - role: hatenablog
      private_values_project: hatena
    - hyper
    - kubernetes
    - mackerel_agent
    # - nix
    - role: nodejs
      versions:
        - "20.5.1"
        - "18.16.0"
        - "10.15.3"
    - role: perl
      versions: ["5.38.0"]
    # - private_values
    - role: python
      versions:
        - "3.11.4"
        - "3.8.8"
    - role: ruby
      versions:
        - "3.2.2"
    - role: rust
      versions:
        - stable
        - nightly
    - sbx
    - scala
    - role: terraform
      versions:
        - "1.5.5"
        - "0.14.11"
    - role: ssh
      private_values_project: hatena
    - vagrant
    - vim
    - role: vscode
      vscode_extensions:
        - EditorConfig.EditorConfig
        - GitHub.vscode-pull-request-github
        - MS-CEINTL.vscode-language-pack-ja
        - Orta.vscode-jest
        - VisualStudioExptTeam.intellicode-api-usage-examples
        - VisualStudioExptTeam.vscodeintellicode
        - betterthantomorrow.calva
        - dbaeumer.vscode-eslint
        - eamodio.gitlens
        - esbenp.prettier-vscode
        - golang.go
        - humao.rest-client
        - jebbs.plantuml
        - marp-team.marp-vscode
        - ms-python.isort
        - ms-python.python
        - ms-toolsai.jupyter
        - ms-toolsai.vscode-jupyter-cell-tags
        - ms-toolsai.vscode-jupyter-slideshow
        - ms-vsliveshare.vsliveshare
        - pgourlain.erlang
        - redhat.java
        - scala-lang.scala
        - scalameta.metals
        - taichi.vscode-textlint
        - vscjava.vscode-java-debug
        - vscjava.vscode-java-dependency
        - vscjava.vscode-java-pack
        - vscjava.vscode-java-test
        - vscjava.vscode-maven
        - vscodevim.vim
    - zsh
