---
- hosts: default
  connection: local
  roles:
    - role: asdf
      asdf_version: v0.7.3
      asdf_plugins:
        - name: erlang
          versions: ["22.0.7"]
          global: "22.0.7"
        - name: elixir
          versions: ["1.9.1-otp-22"]
          global: "1.9.1-otp-22"
        - name: nodejs
          versions: ["10.15.3"]
          global: "10.15.3"
        - name: ruby
          versions: ["2.3.1"]
          global: "2.3.1"
    - dev_dir
    - editorconfig
    - emacs
    - role: git
      user_name: ne-sachirou
      user_email: ne-sachirou@hatena.ne.jp
    - homebrew
    - role: ssh
      private_values_project: hatena
    - vim
    - role: vscode
      vscode_extensions:
        - bung87.vscode-gemfile
        - dbaeumer.vscode-eslint
        - eamodio.gitlens
        - EditorConfig.EditorConfig
        - esbenp.prettier-vscode
        - GitHub.vscode-pull-request-github
        - JakeBecker.elixir-ls
        - jebbs.plantuml
        - marp-team.marp-vscode
        - mjmcloug.vscode-elixir
        - MS-CEINTL.vscode-language-pack-ja
        - ms-python.python
        - ms-vsliveshare.vsliveshare
        - msjsdiag.debugger-for-chrome
        - rebornix.ruby
        - scala-lang.scala
        - scalameta.metals
        - taichi.vscode-textlint
        - vscodevim.vim
    - zsh
