---
- hosts: default
  roles:
    - homebrew
    - role: asdf
      asdf_version: v0.10.2
    - role: clojure
      versions: ["1.10.3.1087"]
    - dev_dir
    - docker
    - editorconfig
    - emacs
    - role: erlang
      versions: ["25.1"]
      elixir:
        versions: ["1.14.0-otp-25"]
    - gcloud
    - role: git
      user_name: ne-sachirou
      user_email: ne-sachirou@hatena.ne.jp
    - role: golang
      versions:
        - "1.19.1"
    - role: hatenablog
      private_values_project: hatena
    - hyper
    - kubernetes
    - mackerel_agent
    # - nix
    - role: nodejs
      versions:
        - "18.12.1"
        - "16.4.2"
        - "14.17.0"
        - "10.15.3"
    - role: perl
      versions: ["5.36.0"]
    # - private_values
    - role: python
      versions:
        - "3.10.7"
        - "3.7.2"
    - role: ruby
      versions:
        - "3.1.2"
        - "2.6.3"
        - "2.5.7"
    - role: rust
      versions:
        - stable
        - nightly
    - sbx
    - scala
    - role: terraform
      versions: ["1.2.8"]
    - role: ssh
      private_values_project: hatena
    - vagrant
    - vim
    - role: vscode
      vscode_extensions:
        - EditorConfig.EditorConfig
        - GitHub.vscode-pull-request-github
        - JakeBecker.elixir-ls
        - MS-CEINTL.vscode-language-pack-ja
        - betterthantomorrow.calva
        - dbaeumer.vscode-eslint
        - eamodio.gitlens
        - esbenp.prettier-vscode
        - golang.go
        - humao.rest-client
        - jebbs.plantuml
        - marp-team.marp-vscode
        - mjmcloug.vscode-elixir
        - ms-python.python
        - ms-toolsai.jupyter
        - ms-vsliveshare.vsliveshare
        - msjsdiag.debugger-for-chrome
        - pgourlain.erlang
        - scala-lang.scala
        - scalameta.metals
        - taichi.vscode-textlint
        - vscodevim.vim
    - zsh
