---
- hosts: default
  roles:
    - homebrew
    - asdf
    - role: clojure
      versions: ["1.11.1.1413"]
    - dev_dir
    - docker
    - editorconfig
    - emacs
    - role: erlang
      versions: ["26.0.2"]
      elixir:
        versions: ["1.15.5-otp-26"]
    - gcloud
    - role: git
      user_name: ne-sachirou
      user_email: ne-sachirou@hatena.ne.jp
    - role: golang
      versions:
        - "1.21.1"
    - role: hatenablog
      private_values_project: hatena
    - hyper
    - kubernetes
    - mackerel_agent
    # - nix
    - role: nodejs
      versions:
        - "20.6.0"
        - "18.16.0"
        - "10.15.3"
    - role: perl
      versions: ["5.38.0"]
    # - private_values
    - role: python
      versions:
        - "3.11.4"
        - "3.8.8"
    - role: ruby
      versions:
        - "3.2.2"
    - role: rust
      versions:
        - stable
        - nightly
    - sbx
    - scala
    - the_silver_searcher
    - role: terraform
      versions:
        - "1.5.5"
        - "0.14.11"
    - role: ssh
      private_values_project: hatena
    - vagrant
    - vim
    - role: vscode
      vscode_extensions:
        - EditorConfig.EditorConfig
        - GitHub.codespaces
        - GitHub.copilot
        - GitHub.copilot-chat
        - GitHub.vscode-pull-request-github
        - MS-CEINTL.vscode-language-pack-ja
        - betterthantomorrow.calva
        - betterthantomorrow.calva-spritz
        - dbaeumer.vscode-eslint
        - eamodio.gitlens
        - esbenp.prettier-vscode
        - github.vscode-github-actions
        - golang.go
        - ms-vsliveshare.vsliveshare
        - scala-lang.scala
        - scalameta.metals
        - vscodevim.vim
    - zsh
