---
- hosts: default
  roles:
    - homebrew
    - role: asdf
      asdf_version: v0.8.1
    - role: clojure
      versions: ["1.10.3.1029"]
    - dev_dir
    - docker
    - editorconfig
    - emacs
    - role: erlang
      versions: ["24.1.5"]
      elixir:
        versions: ["1.12.3-otp-24"]
    - role: git
      user_name: ne-sachirou
      user_email: ne-sachirou@hatena.ne.jp
    - role: golang
      versions:
        - "1.17.3"
        - "1.16.7"
        - "1.14.13"
        - "1.12.17"
    - role: hatenablog
      private_values_project: hatena
    - hyper
    - kubernetes
    - mackerel_agent
    - role: nodejs
      versions:
        - "16.13.0"
        - "14.17.6"
        - "14.17.0"
        - "14.15.4"
        - "12.20.0"
        - "10.15.3"
    - role: perl
      versions: ["5.34.0"]
    # - private_values
    - role: python
      versions:
        - "3.10.0"
        - "3.7.2"
    - role: ruby
      versions:
        # - "3.0.2"
        - "2.6.3"
        - "2.5.7"
    - role: rust
      versions:
        - stable
        - nightly
    - scala
    - role: ssh
      private_values_project: hatena
    - vagrant
    - vim
    - role: vscode
      vscode_extensions:
        - EditorConfig.EditorConfig
        - GitHub.vscode-pull-request-github
        - JakeBecker.elixir-ls
        - MS-CEINTL.vscode-language-pack-ja
        - betterthantomorrow.calva
        - dbaeumer.vscode-eslint
        - eamodio.gitlens
        - esbenp.prettier-vscode
        - golang.go
        - humao.rest-client
        - jebbs.plantuml
        - marp-team.marp-vscode
        - mjmcloug.vscode-elixir
        - ms-python.python
        - ms-toolsai.jupyter
        - ms-vsliveshare.vsliveshare
        - msjsdiag.debugger-for-chrome
        - pgourlain.erlang
        - scala-lang.scala
        - scalameta.metals
        - taichi.vscode-textlint
        - vscodevim.vim
    - zsh
