---
- hosts: default
  roles:
    - apt
    - role: asdf
      asdf_version: v0.11.3
    - role: clojure
      versions: ["1.11.1.1208"]
    # - docker
    - editorconfig
    - emacs
    - role: erlang
      versions: ["25.2.1"]
      elixir:
        versions: ["1.14.3-otp-25"]
    - role: git
      user_name: ne-sachirou
      user_email: utakata.c4se@gmail.com
    - role: nodejs
      versions: ["18.16.0"]
    - private_values
    - role: python
      versions: ["3.11.1"]
    - role: ruby
      versions: ["3.2.0"]
    - sbx
    - vim
    - zsh
# ~/profile
# export DOCKER_HOST="tcp://0.0.0.0:2375"
# PATH="$HOME/.poetry/bin:$PATH"
# export PATH

# ~/.bashrc
# . $HOME/.asdf/asdf.sh
# . $HOME/.asdf/completions/asdf.bash
# eval "$(direnv hook bash)"
# alias cd-dev="cd /mnt/c/Users/c4se/dev"
# DISPLAY=:0.0
# LIBGL_ALWAYS_INDIRECT=1
# export DISPLAY LIBGL_ALWAYS_INDIRECT
