---
- hosts: default
  roles:
    - apt
    - role: asdf
      asdf_version: v0.7.8
    - role: clojure
      versions: ["1.10.1"]
    # - docker
    - editorconfig
    - emacs
    - role: erlang
      versions: ["22.3.4"]
      elixir:
        versions: ["1.10.2-otp-22"]
    - role: git
      user_name: ne-sachirou
      user_email: utakata.c4se@gmail.com
    - role: haskell
      versions: ["8.10.1"]
    - role: nodejs
      versions: ["14.2.0"]
    - private-values
    - role: python
      versions: ["3.8.2"]
    - vim
    - zsh
# ~/profile
# export DOCKER_HOST="tcp://0.0.0.0:2375"
# PATH="$HOME/.poetry/bin:$PATH"
# export PATH

# ~/.bashrc
# . $HOME/.asdf/asdf.sh
# . $HOME/.asdf/completions/asdf.bash
# eval "$(direnv hook bash)"
# alias cd-dev="cd /mnt/c/Users/c4se/dev"
# DISPLAY=:0.0
# LIBGL_ALWAYS_INDIRECT=1
# export DISPLAY LIBGL_ALWAYS_INDIRECT
