---
- hosts: default
  roles:
    - apt
    - role: asdf
      asdf_version: v0.10.2
    - role: clojure
      versions: ["1.10.3.1087"]
    # - docker
    - editorconfig
    - emacs
    - role: erlang
      versions: ["25.1"]
      elixir:
        versions: ["1.14.0-otp-25"]
    - role: git
      user_name: ne-sachirou
      user_email: utakata.c4se@gmail.com
    - role: nodejs
      versions: ["18.10.0"]
    - private_values
    - role: python
      versions: ["3.10.6"]
    - role: ruby
      versions: ["3.1.2"]
    - sbx
    - vim
    - zsh
# ~/profile
# export DOCKER_HOST="tcp://0.0.0.0:2375"
# PATH="$HOME/.poetry/bin:$PATH"
# export PATH

# ~/.bashrc
# . $HOME/.asdf/asdf.sh
# . $HOME/.asdf/completions/asdf.bash
# eval "$(direnv hook bash)"
# alias cd-dev="cd /mnt/c/Users/c4se/dev"
# DISPLAY=:0.0
# LIBGL_ALWAYS_INDIRECT=1
# export DISPLAY LIBGL_ALWAYS_INDIRECT
