---
- hosts: default
  roles:
    - apt
    - role: asdf
      asdf_version: v0.9.0
    - role: clojure
      versions: ["1.10.3.1040"]
    # - docker
    - editorconfig
    - emacs
    - role: erlang
      versions: ["24.1.7"]
      elixir:
        versions: ["1.13.0-otp-24"]
    - role: git
      user_name: ne-sachirou
      user_email: utakata.c4se@gmail.com
    - role: haskell
      versions: ["9.2.1"]
    - role: nodejs
      versions: ["16.13.1"]
    - private_values
    - role: python
      versions: ["3.10.1"]
    - role: ruby
      versions: ["3.0.2"]
    - vim
    - zsh
# ~/profile
# export DOCKER_HOST="tcp://0.0.0.0:2375"
# PATH="$HOME/.poetry/bin:$PATH"
# export PATH

# ~/.bashrc
# . $HOME/.asdf/asdf.sh
# . $HOME/.asdf/completions/asdf.bash
# eval "$(direnv hook bash)"
# alias cd-dev="cd /mnt/c/Users/c4se/dev"
# DISPLAY=:0.0
# LIBGL_ALWAYS_INDIRECT=1
# export DISPLAY LIBGL_ALWAYS_INDIRECT
