---
- hosts: default
  roles:
    - apt
    - role: asdf
      asdf_version: v0.8.1
    - role: clojure
      versions: ["1.10.3.967"]
    # - docker
    - editorconfig
    - emacs
    - role: erlang
      versions: ["24.1"]
      elixir:
        versions: ["1.12.3-otp-24"]
    - role: git
      user_name: ne-sachirou
      user_email: utakata.c4se@gmail.com
    - role: haskell
      versions: ["9.0.1"]
    - role: nodejs
      versions: ["16.9.1"]
    - private_values
    - role: python
      versions:
        - "3.9.7"
        - "3.7.9" # Transcrypt needs 3.7.x
    - role: ruby
      versions: ["3.0.2"]
    - vim
    - zsh
# ~/profile
# export DOCKER_HOST="tcp://0.0.0.0:2375"
# PATH="$HOME/.poetry/bin:$PATH"
# export PATH

# ~/.bashrc
# . $HOME/.asdf/asdf.sh
# . $HOME/.asdf/completions/asdf.bash
# eval "$(direnv hook bash)"
# alias cd-dev="cd /mnt/c/Users/c4se/dev"
# DISPLAY=:0.0
# LIBGL_ALWAYS_INDIRECT=1
# export DISPLAY LIBGL_ALWAYS_INDIRECT
