---
- name: asdf install elixir
  asdf:
    plugin: elixir
    versions: "{{ elixir.versions }}"
    global: "{{ elixir.global | default(elixir.versions[0]) }}"

- include_tasks: mix.yml
  loop: "{{ elixir.versions }}"
  vars:
    version: "{{ item }}"
