---
- name: asdf plugin add erlang
  command: asdf plugin add erlang
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/erlang"
  ignore_errors: true

- name: asdf install erlang
  command: "asdf install erlang {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/installs/erlang/{{ item }}"
  with_items: "{{ versions }}"

- name: asdf global erlang
  command: "asdf global erlang {{ global | default(versions[0]) }}"

- name: asdf list erlang
  command: asdf list erlang
  register: asdf_list_erlang
  changed_when: false
  check_mode: false

- name: asdf uninstall erlang
  command: "asdf uninstall erlang {{ item }}"
  with_items: "{{ asdf_list_erlang.stdout.split('\n') | map('trim') | list }}"
  when: >-
    item not in versions

- name: Install rebar3
  get_url:
    url: https://s3.amazonaws.com/rebar3/rebar3
    dest: /usr/local/bin/rebar3
    mode: "0755"
    owner: root
  become: true

- name: ~/.config/rebar3
  file: path={{ ansible_env.HOME }}/.config/rebar3 state=directory

- name: rebar.config
  file: path={{ ansible_env.HOME }}/.config/rebar3/rebar.config src={{ role_path }}/files/rebar.config state=link

- name: rebar3 local install
  command: rebar3 local install

- import_tasks: elixir.yml
