---
- name: asdf install erlang
  asdf:
    plugin: erlang
    versions: "{{ versions }}"
    global: "{{ global | default(versions[0]) }}"

- name: Install rebar3
  get_url:
    url: https://s3.amazonaws.com/rebar3/rebar3
    dest: /usr/local/bin/rebar3
    mode: "0755"
    owner: root
  become: true

- name: ~/.config/rebar3
  file: path={{ ansible_env.HOME }}/.config/rebar3 state=directory

- name: rebar.config
  file: path={{ ansible_env.HOME }}/.config/rebar3/rebar.config src={{ role_path }}/files/rebar.config state=link

- name: rebar3 local install
  command: rebar3 local install

- import_tasks: elixir.yml
