---
- name: Lookup `code --list-extensions`
  command: code --list-extensions
  register: vscode_installed_extensions
  changed_when: false
  check_mode: false

- name: Install extensions
  command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  when: >-
    item not in vscode_installed_extensions.stdout

- name: Uninstall extensions
  command: code --uninstall-extension {{ item }}
  with_items: "{{ vscode_installed_extensions.stdout.split('\n') }}"
  when: >-
    item not in vscode_extensions
