# -*- mode: ruby -*-

tap 'AdoptOpenJDK/openjdk'
tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ansible'
brew 'ansible-lint'
brew 'argoproj/tap/argo'
brew 'autoconf'
brew 'assh'
brew 'awscli'
brew 'awslogs'
brew 'azure-cli'
# brew 'chromedriver'
# brew 'clojure'
# brew 'clojurescript'
# brew 'closure-compiler'
brew 'coreutils'
brew 'cpanminus'
brew 'direnv'
brew 'emacs'
brew 'fswatch'
brew 'fzy'
brew 'ghc'
brew 'git-now'
brew 'go'
brew 'gpg'
brew 'hadolint'
brew 'haskell-stack'
brew 'hlint'
brew 'hub'
brew 'imageoptim-cli'
# brew 'istioctl'
brew 'jasper', link: true # PlantUML JPEG2000
brew 'jq'
# brew 'kubernetes-cli'
# brew 'kubernetes-helm'
brew 'kustomize'
# brew 'leiningen'
brew 'mackerelio/mackerel-agent/mackerel-agent', restart_service: true
brew 'mackerelio/mackerel-agent/mkr'
brew 'mas'
brew 'noti'
brew 'openapi-generator'
brew 'peco'
brew 'pipenv'
brew 'plantuml'
brew 'ponyc'
brew 'postgresql@9.6'
brew 'pstree'
brew 'redis'
# brew 'rust'
brew 'sbt'
brew 'scalacenter/bloop/bloop'
brew 'shellcheck'
brew 'sl'
brew 'sshuttle'
brew 'stern'
brew 'the_silver_searcher'
# brew 'terraform'
brew 'topgrade'
brew 'tree'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'yamllint'
brew 'zsh'

cask 'adoptopenjdk8'
cask 'adoptopenjdk11'
# cask 'android-file-transfer'
# cask 'android-ndk'
# cask 'android-sdk'
cask 'dash'
cask 'discord'
cask 'firefox'
# cask 'fontforge'
cask 'gimp'
# cask 'google-cloud-sdk'
cask 'imageoptim'
# cask 'inkscape'
cask 'jasper'
cask 'karabiner-elements'
cask 'notion'
cask 'vagrant'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'visual-studio-code'
cask 'xquartz'

# mas 'LINE', id: 539883307
mas 'Slack', id: 803453959
mas 'feedly', id: 865500966
