tap 'caskroom/cask'
# tap 'goby-lang/goby'
tap 'homebrew/bundle'

brew 'ansible'
brew 'ansible-lint'
# brew 'argoproj/tap/argo'
brew 'autoconf'
# brew 'aspell', args: ["with-lang-eo", "with-lang-ja"]
brew 'assh'
brew 'awscli'
brew 'awslogs'
# brew 'chromedriver'
# brew 'clojure'
# brew 'clojurescript'
# brew 'closure-compiler'
brew 'coreutils'
brew 'direnv'
brew 'emacs'
brew 'fswatch'
brew 'fzy'
brew 'ghc'
brew 'git-now'
brew 'go'
# brew 'goby'
brew 'gpg'
brew 'hadolint'
brew 'haskell-stack'
# brew 'heroku'
# brew 'hexedit'
brew 'hlint'
brew 'hub'
brew 'imageoptim-cli'
# brew 'istioctl'
brew 'jasper', link: true # PlantUML JPEG2000
# brew 'jid'
brew 'jq'
# brew 'kubernetes-cli'
# brew 'kubernetes-helm'
brew 'kustomize'
# brew 'libav'
# brew 'libsodium'
# brew 'leiningen'
brew 'mackerelio/mackerel-agent/mackerel-agent'
brew 'mackerelio/mackerel-agent/mkr'
brew 'mas'
# brew 'mycli'
# brew 'mysql'
# brew 'nghttp2' # h2load
brew 'noti'
# brew 'nyuichi/satysfi/satysfi'
brew 'openapi-generator'
# brew 'p7zip'
brew 'peco'
# brew 'pipenv'
brew 'plantuml'
brew 'ponyc'
brew 'postgresql@9.6'
brew 'pstree'
# brew 'redis'
# brew 'rust'
# brew 'sbt'
# brew 'scala'
brew 'shellcheck'
brew 'sl'
brew 'sshuttle'
brew 'stern'
brew 'the_silver_searcher'
# brew 'terraform'
brew 'topgrade'
brew 'tree'
brew 'vim'
brew 'watch'
brew 'wget'
# brew 'wrk'
brew 'yamllint'
# brew 'youtube-dl'
# brew 'zlib'
brew 'zsh'

# cask 'android-file-transfer'
# cask 'android-ndk'
# cask 'android-sdk'
cask 'dash'
cask 'firefox'
# cask 'fontforge'
cask 'gimp'
# cask 'google-cloud-sdk'
cask 'imageoptim'
# cask 'inkscape'
# cask 'jasper'
# cask 'caskroom/versions/java8'
# cask 'java'
cask 'karabiner-elements'
cask 'notion'
# cask 'vlc'
cask 'visual-studio-code'
cask 'xquartz'

# mas 'Evernote', id: 406056744
# mas 'LastPass', id: 926036361
# mas 'LINE', id: 539883307
mas 'Slack', id: 803453959
mas 'feedly', id: 865500966

# -*- mode: ruby -*-
