---
- name: asdf install clojure
  asdf:
    plugin: clojure
    versions: "{{ versions }}"
    global: "{{ global | default(versions[0]) }}"

- name: ~/.m2
  file: path={{ ansible_env.HOME }}/.m2 state=directory

- name: ~/.m2/settings.xml
  copy:
    dest: "{{ ansible_env.HOME }}/.m2/settings.xml"
    src: "{{ lookup('private_values', 'path dotfiles') }}/settings.xml"

- name: Install babashka
  shell: |
    bash <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
  args:
    creates: /usr/local/bin/bb
