---
- name: asdf plugin add clojure
  command: asdf plugin add clojure
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/clojure"
  ignore_errors: true

- name: asdf install clojure
  command: "asdf install clojure {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/installs/clojure/{{ item }}"
  with_items: "{{ versions }}"

- name: asdf global clojure
  command: "asdf global clojure {{ global | default(versions[0]) }}"

- name: asdf list clojure
  command: asdf list clojure
  register: asdf_list_clojure
  changed_when: false
  check_mode: false

- name: asdf uninstall clojure
  command: "asdf uninstall clojure {{ item }}"
  with_items: "{{ asdf_list_clojure.stdout.split('\n') | map('trim') | list }}"
  when: >-
    item not in versions
