---
- name: asdf install nodejs
  asdf:
    plugin: nodejs
    versions: "{{ versions }}"
    global: "{{ global | default(versions[0]) }}"

- include_tasks: npm.yml
  loop: "{{ versions }}"
  vars:
    version: "{{ item }}"
