---
- name: asdf install nodejs
  asdf:
    plugin: nodejs
    versions: "{{ versions }}"
    global: "{{ global | default(versions[0]) }}"

- name: ~/.npmrc
  file: path={{ ansible_env.HOME }}/.npmrc src={{ role_path }}/files/.npmrc

- include_tasks: npm.yml
  loop: "{{ versions }}"
  vars:
    version: "{{ item }}"
