---
# - name: 1.0/build.sbt
#   file: path={{ ansible_env.HOME }}/.sbt/1.0/build.sbt src={{ role_path }}/files/build.sbt state=link
#
# - name: 1.0/plugins
#   file: path={{ ansible_env.HOME }}/.sbt/1.0/plugins state=directory
#
# - name: 1.0/plugins.sbt
#   file: path={{ ansible_env.HOME }}/.sbt/1.0/plugins/plugins.sbt src={{ role_path }}/files/plugins.sbt state=link

- name: metals-emacs
  command: |
   coursier bootstrap \
      --java-opt -XX:+UseG1GC \
      --java-opt -XX:+UseStringDeduplication  \
      --java-opt -Xss4m \
      --java-opt -Xms100m \
      org.scalameta:metals_2.13:1.5.3 -o ~/.local/bin/metals -f
