---
- name: asdf install python
  asdf:
    plugin: python
    versions: "{{ versions }}"
    global: "{{ global | default(versions[0]) }}"

- include: pip.yml
  loop: "{{ versions }}"
  vars:
    version: "{{ item }}"
