tap 'homebrew/bundle'
tap 'caskroom/cask'
brew 'ansible'
brew 'ansible-lint'
brew 'crystal-lang'
brew 'direnv'
brew 'emacs'
brew 'erlang'
brew 'haskell-stack'
brew 'heroku'
brew 'hub'
brew 'jq'
brew 'libav'
brew 'mas'
brew 'mycli'
brew 'node'
brew 'peco'
brew 'shellcheck'
brew 'sl'
brew 'the_silver_searcher'
brew 'vim'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh'
cask 'gimp'
mas 'Evernote', id: 406056744
mas 'Slack', id: 803453959
