---
- name: mix do local.hex --force, local.rebar --force
  command: mix do local.hex --force, local.rebar --force

- name: mix archive.install hex phx_new --force
  command: mix archive.install hex phx_new --force
