---
# - name: Install asdf
#   git:
#     repo: https://github.com/asdf-vm/asdf.git
#     version: "{{ asdf_version }}"
#     dest: "{{ ansible_env.HOME }}/.asdf"

- name: ~/.asdfrc
  file: path={{ ansible_env.HOME }}/.asdfrc src={{ role_path }}/files/.asdfrc state=link

- name: Setip Zsh complition
  shell: |
    mkdir -p "${ASDF_DATA_DIR:-$HOME/.asdf}/completions" && \
    asdf completion zsh > "${ASDF_DATA_DIR:-$HOME/.asdf}/completions/_asdf"

- name: asdf plugin update --all
  command: asdf plugin update --all
# locate .tool-version | sort | xargs -I{} sh -c 'echo {} && sort {} | awk '"'"'{print"\t"$0}'"'"' && echo'
