---
- name: npm install
  shell: >-
    set -ex && \
    asdf local nodejs {{ item[0] }} && \
    npm install -g {{ item[1] }}
  with_nested:
    - "{{ asdf_plugins | json_query('[?name==`nodejs`].versions') | join(',') }}"
    - - "@google/clasp"
      - "@marp-team/marp-cli"
      - aws-cdk
      - npm-check-updates
      - npm-safety-updater
      - prettier
      - textlint
      - typescript
      - typescript-language-server
      - yarn
      - yarn-deduplicate

- name: npm update -g
  shell: >-
    set -ex && \
    asdf local nodejs {{ item }} && \
    npm update -g
  with_items: "{{ asdf_plugins | json_query('[?name==`nodejs`].versions') | join(',') }}"
