---
- name: Install package
  command: npm install -g {{ item }}
  with_items:
    - "@google/clasp"
    - "@marp-team/marp-cli"
    - aws-cdk
    - npm-check-updates
    - npm-safety-updater
    - prettier
    - textlint
    - typescript
    - widdershins
    - yarn-deduplicate

- name: npm update
  command: npm update -g
