---
- name: gem install
  shell: >-
    set -ex && \
    asdf local ruby {{ item[0] }} && \
    gem install {{ item[1] }}
  with_nested:
    - "{{ asdf_plugins | json_query('[?name==`ruby`].versions') | join(',') }}"
    - # - inesita
      # - rails
      - rubocop
      - serverspec

- name: gem update
  shell: >-
    set -ex && \
    asdf local ruby {{ item }} && \
    gem update --system && \
    gem update
  with_items: "{{ asdf_plugins | json_query('[?name==`ruby`].versions') | join(',') }}"
