---
- name: gem install
  command: gem install {{ item }}
  with_items:
    # - inesita
    # - rails
    - rubocop

- name: gem update
  shell: >-
    set -ex && \
    gem update --system && \
    gem update
