---
# - name: Setup rbenv-default-gems
#   lineinfile: dest={{rbenv_root.stdout}}/default-gems line={{item}} create=yes
#   with_items:
#     - bundler
#     - command_socksify
#     - rails
#     - rubocop

- name: gem update
  shell: >-
    set -ex && \
    gem update --system && \
    gem update
