---
- name: gem install
  command: gem install {{ item }}
  with_items:
    - faastruby
    - inesita
    - rails
    - rubocop

- name: gem update
  shell: >-
    set -ex && \
    gem update --system && \
    gem update
