---
- name: ~/.zprofile
  file: path={{ ansible_env.HOME }}/.zprofile src={{ role_path }}/files/.zprofile state=link

- name: ~/.zshrc
  template: dest={{ ansible_env.HOME }}/.zshrc src={{ role_path }}/templates/.zshrc.j2

- name: ~/.zsh/
  file: path={{ ansible_env.HOME }}/.zsh state=directory

- name: Local ~/.zsh/*.zsh
  file: path={{ ansible_env.HOME }}/.zsh/{{ item.key }} src={{ item.value }} state=link
  with_dict:
    .zshrc.darwin: "{{ role_path }}/files/.zshrc.darwin"

- name: Remote ~/.zsh/*.zsh
  get_url: url={{ item.value }} dest={{ ansible_env.HOME }}/.zsh/{{ item.key }}
  with_dict:
    _git: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh
    assh_autocomplete.zsh: https://raw.githubusercontent.com/moul/advanced-ssh-config/master/contrib/completion/zsh_autocomplete
    git-completion.bash: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    git-prompt.sh: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    lazyenv.bash: https://raw.githubusercontent.com/takezoh/lazyenv/master/lazyenv.bash

- name: zi
  git: repo=https://github.com/z-shell/zi.git depth=1 dest={{ ansible_env.HOME }}/.zi/bin

- name: zi self-update
  command: zsh -c '. ~/.zshrc && zi self-update'

- name: zi update --all
  command: zsh -c '. ~/.zshrc && zi update --all'

- name: ~/.local/bin/
  file: path={{ ansible_env.HOME }}/.local/bin/ state=directory
