---
- name: ~/.gitconfig
  template: dest={{ ansible_env.HOME }}/.gitconfig src={{ role_path }}/templates/.gitconfig.j2

- name: ~/.gitignore
  file: path={{ ansible_env.HOME }}/.gitignore src={{ role_path }}/files/.gitignore state=link

- import_tasks: git-subrepo.yml
