---
- name: brew tap Homebrew/bundle
  homebrew_tap: tap=Homebrew/bundle

- name: brew update
  command: brew update

- name: brew bundle
  shell: brew bundle --file={{ role_path }}/files/.Brewfile || true

- name: brew bundle cleanup
  command: brew bundle cleanup -f --file={{ role_path }}/files/.Brewfile

- name: brew cleanup
  command: brew cleanup --prune 7

- import_tasks: terminal.yml
