---
- name: Tap Homebrew Bundle
  homebrew_tap: tap=Homebrew/bundle

- name: brew update
  command: brew update

- name: brew bundle
  shell: brew bundle --file={{ role_path }}/files/.Brewfile || true

- name: brew bundle cleanup
  command: brew bundle cleanup --file={{ role_path }}/files/.Brewfile --force

- name: brew cleanup
  command: brew cleanup --prune 7

- import_tasks: terminal.yml
