---
- name: Tap Homebrew Bundle
  homebrew_tap: tap=Homebrew/bundle

- name: brew update
  command: brew update

- name: brew bundle
  command: brew bundle --file={{role_path}}/files/.Brewfile

- name: brew bundle clean
  command: brew bundle cleanup --file={{role_path}}/files/.Brewfile

- name: brew upgrade
  command: brew upgrade

- name: mas upgrade
  command: mas upgrade
