---
- name: asdf plugin add perl
  command: asdf plugin add perl https://github.com/chrolis/asdf-perl.git
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/perl"
  ignore_errors: true

- name: asdf install perl
  command: "asdf install perl {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/installs/perl/{{ item }}"
  with_items: "{{ versions }}"

- name: cpanm
  shell: >-
    set -ex && \
    asdf local perl {{ item[0] }} && \
    cpanm {{ item[1] }} && \
    asdf reshim perl
  with_nested:
    - "{{ versions }}"
    - - Carton

- name: asdf global perl
  command: "asdf global perl {{ global | default(versions[0]) }}"

- name: asdf list perl
  command: asdf list perl
  register: asdf_list_perl
  changed_when: false
  check_mode: false

- name: asdf uninstall perl
  command: "asdf uninstall perl {{ item }}"
  with_items: "{{ asdf_list_perl.stdout.split('\n') | map('trim') | list }}"
  when: >-
    item not in versions
