---
# Use a third party plugin.
- name: asdf plugin add perl
  command: asdf plugin add perl https://github.com/chrolis/asdf-perl.git
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/perl"
  ignore_errors: true

- name: asdf install perl
  asdf:
    plugin: perl
    versions: "{{ versions }}"
    global: "{{ global | default(versions[0]) }}"

- include_tasks: cpanm.yml
  loop: "{{ versions }}"
  vars:
    version: "{{ item }}"
