---
- name: ~/.emacs.d
  file: path={{ansible_env.HOME}}/.emacs.d state=directory

- name: ~/.emacs.d/init.el
  file: path={{ansible_env.HOME}}/.emacs.d/init.el src={{role_path}}/files/emacs/init.el state=link

- name: ~/.emacs-live.el
  file: path={{ansible_env.HOME}}/.emacs-live.el src={{role_path}}/files/emacs/.emacs-live.el state=link

- name: emacsserver
  file: path={{ansible_env.HOME}}/.local/bin/emacsserver src={{role_path}}/files/emacs/emacsserver state=link

- name: emacs-package
  file: path={{ansible_env.HOME}}/.local/bin/emacs-package src={{role_path}}/files/emacs/emacs-package state=link

- name: package-get
  command: emacs-package update
