---
- name: ~/.zprofile
  file: path={{ansible_env.HOME}}/.zprofile src={{role_path}}/files/zsh/.zprofile state=link

- name: ~/.zshrc
  template: dest={{ansible_env.HOME}}/.zshrc src={{role_path}}/templates/.zshrc.j2

- name: ~/.zsh
  file: path={{ansible_env.HOME}}/.zsh state=directory

- name: Local ~/.zsh/*.zsh
  file: path={{ansible_env.HOME}}/.zsh/{{item.key}} src={{item.value}} state=link
  with_dict:
    .zshrc.darwin: "{{role_path}}/files/zsh/.zshrc.darwin"

- name: Remote ~/.zsh/*.zsh
  get_url: url={{item.value}} dest={{ansible_env.HOME}}/.zsh/{{item.key}}
  with_dict:
    _git: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh
    _git-bug: https://raw.githubusercontent.com/MichaelMure/git-bug/master/misc/zsh_completion/git-bug
    osx.plugin.zsh: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/plugins/osx/osx.plugin.zsh
    git-completion.bash: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    git-prompt.sh: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh

- name: zplug
  git: repo=https://github.com/zplug/zplug.git depth=1 dest={{ansible_env.HOME}}/.zplug

- name: zplug update
  command: zsh -c 'source ~/.zshrc; zplug update'
