---
- name: update-alternatives --set editor /usr/bin/vim.basic
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
  become: true
  when: ansible_distribution == "Ubuntu"

- name: ~/.vim/
  file: path={{ ansible_env.HOME }}/.vim state=directory

- name: init.vim
  file: path={{ item }} src={{ role_path }}/files/init.vim state=link
  with_items:
    # - "{{ ansible_env.HOME }}/.vim/init.vim" # for NeoVim
    - "{{ ansible_env.HOME }}/.vimrc"

- name: ~/.vim/autoload/
  file: path={{ ansible_env.HOME }}/.vim/autoload state=directory

- name: vim-plug
  get_url:
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Plug
  command: vim -c "silent exe 'PlugUpgrade | PlugUpdate | qa'"
