---
- name: ~/.vim/
  file: path={{ ansible_env.HOME }}/.vim state=directory

- name: init.vim
  file: path={{ item }} src={{ role_path }}/files/init.vim state=link
  with_items:
    - "{{ ansible_env.HOME }}/.vim/init.vim"
    - "{{ ansible_env.HOME }}/.vimrc"

- name: ~/.vim/autoload/
  file: path={{ ansible_env.HOME }}/.vim/autoload state=directory

- name: vim-plug
  get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest={{ ansible_env.HOME }}/.vim/autoload/plug.vim

- name: Plug
  command: vim -c "silent exe 'PlugUpgrade | PlugUpdate | qa'"
