---
- name: asdf plugin add ruby
  command: asdf plugin add ruby
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/ruby"
  ignore_errors: true

- name: asdf install ruby
  command: "asdf install ruby {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/installs/ruby/{{ item }}"
  with_items: "{{ versions }}"

- name: gem install
  shell: >-
    set -ex && \
    asdf local ruby {{ item[0] }} && \
    gem install {{ item[1] }} && \
    asdf reshim ruby
  with_nested:
    - "{{ versions }}"
    - - rubocop
      - serverspec

- name: gem update
  shell: >-
    set -ex && \
    asdf local ruby {{ item }} && \
    gem update --system && \
    gem update
  with_items: "{{ versions }}"

- name: asdf global ruby
  command: "asdf global ruby {{ global | default(versions[0]) }}"

- name: asdf list ruby
  command: asdf list ruby
  register: asdf_list_ruby
  changed_when: false
  check_mode: false

- name: asdf uninstall ruby
  command: "asdf uninstall ruby {{ item }}"
  with_items: "{{ asdf_list_ruby.stdout.split('\n') | map('trim') | list }}"
  when: >-
    item not in versions
