---
- name: asdf install ruby
  asdf:
    plugin: ruby
    versions: "{{ versions }}"
    global: "{{ global | default(versions[0]) }}"

- include: gem.yml
  loop: "{{ versions }}"
  vars:
    version: "{{ item }}"
